version: "3"
services:
  wyoming-glados:
    image: captnspdr/wyoming-glados:latest-amd64
    container_name: wyoming-glados
    ports:
      - 10201:10201
    volumes:
      - ./models:/usr/src/models:rw
    environment:
      - STREAMING=true
      - DEBUG=false
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
