version: "3"
services:
  wyoming-glados:
    build: .
    container_name: wyoming-glados
    ports:
      - 10201:10201
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
