version: "3"
services:
  wyoming-glados:
    image: captnspdr/wyoming-glados:latest-igpu
    container_name: wyoming-glados
    ports:
      - 10201:10201
    environment:
      - streaming=true
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
