version: "3"
services:
  wyoming-glados:
    image: captnspdr/wyoming-glados:latest-igpu
    container_name: wyoming-glados
    ports:
      - 10201:10201
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - ./models:/usr/src/models:rw
    environment:
      - STREAMING=true
      - DEBUG=false
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
