version: "3"
services:
  wyoming-glados:
    build: Dockerfile.igpu
    context: .
    dockerfile: Dockerfile
    image: wyoming-glados
    container_name: wyoming-glados
    ports:
      - 10201:10201
    environment:
      - streaming=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
